name = "blackrent-upload-worker"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[vars]
R2_PUBLIC_URL = "https://blackrent-storage.9ccdca0d876e24bd9acefabe56f94f53.r2.dev"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "blackrent-storage"
preview_bucket_name = "blackrent-storage-dev"

[env.production]
name = "blackrent-upload-worker"

[env.staging]
name = "blackrent-upload-worker-staging" 