# Cloudflare Wrangler Configuration for BlackRent R2 Storage
name = "blackrent-r2"
main = "src/index.ts"
compatibility_date = "2025-10-12"

# R2 Bucket Configuration
[[r2_buckets]]
binding = "BLACKRENT_BUCKET"
bucket_name = "blackrent"
preview_bucket_name = "blackrent-dev"

# Environment Variables (use .dev.vars for local development)
# Do NOT commit sensitive credentials here

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# Build configuration
[build]
command = "pnpm build"

# Observability
[observability]
enabled = true

