/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/store` | `/store`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/booking/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/booking`; params?: Router.UnknownInputParams; } | { pathname: `/booking/success`; params?: Router.UnknownInputParams; } | { pathname: `/store/cart`; params?: Router.UnknownInputParams; } | { pathname: `/store/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/store/success`; params?: Router.UnknownInputParams; } | { pathname: `/profile/bookings`; params?: Router.UnknownInputParams; } | { pathname: `/vehicle/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/store` | `/store`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/booking/confirmation`; params?: Router.UnknownOutputParams; } | { pathname: `/booking`; params?: Router.UnknownOutputParams; } | { pathname: `/booking/success`; params?: Router.UnknownOutputParams; } | { pathname: `/store/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/store/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/store/success`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/bookings`; params?: Router.UnknownOutputParams; } | { pathname: `/vehicle/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/catalog${`?${string}` | `#${string}` | ''}` | `/catalog${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/store${`?${string}` | `#${string}` | ''}` | `/store${`?${string}` | `#${string}` | ''}` | `/auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/booking/confirmation${`?${string}` | `#${string}` | ''}` | `/booking${`?${string}` | `#${string}` | ''}` | `/booking/success${`?${string}` | `#${string}` | ''}` | `/store/cart${`?${string}` | `#${string}` | ''}` | `/store/checkout${`?${string}` | `#${string}` | ''}` | `/store/success${`?${string}` | `#${string}` | ''}` | `/profile/bookings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/store` | `/store`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/booking/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/booking`; params?: Router.UnknownInputParams; } | { pathname: `/booking/success`; params?: Router.UnknownInputParams; } | { pathname: `/store/cart`; params?: Router.UnknownInputParams; } | { pathname: `/store/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/store/success`; params?: Router.UnknownInputParams; } | { pathname: `/profile/bookings`; params?: Router.UnknownInputParams; } | `/vehicle/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/vehicle/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
