// Central icon mapping system for BlackRent
// This allows changing icons globally from one place

import {
  // Navigation & Actions
  Plus,
  Minus,
  Edit,
  Trash2,
  X,
  Check,
  Search,
  Filter,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  
  // Business & Finance
  Car,
  Building,
  User,
  Users,
  Calendar,
  Clock,
  CreditCard,
  Euro,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  Percent,
  
  // Communication
  Mail,
  Phone,
  MessageSquare,
  Bell,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  AlertTriangle,
  BellOff,
  
  // Files & Documents
  FileText,
  File,
  Download,
  Upload,
  Folder,
  FolderOpen,
  Image,
  Camera,
  Eye,
  EyeOff,
  
  // Settings & Tools
  Settings,
  Cog,
  Wrench,
  Shield,
  Lock,
  Unlock,
  Key,
  Database,
  Server,
  Cloud,
  
  // Status & Indicators
  Circle,
  Square,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Tag,
  Bookmark,
  
  // Layout & UI
  Menu,
  Grid,
  List,
  Layout,
  Columns,
  Maximize,
  Minimize,
  MoreHorizontal,
  MoreVertical,
  
  // Time & Date
  CalendarDays,
  Clock3,
  Timer,
  History,
  
  // Transportation
  Truck,
  Bus,
  Plane,
  Train,
  Bike,
  MapPin,
  Navigation,
  
  // Technology
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryLow,
  Power,
  Zap,
  Monitor,
  Smartphone,
  Tablet,
  
  // Additional missing icons
  Receipt,
  UserPlus,
  Calculator,
  Gauge,
  FileBarChart,
  Activity,
  Wand2,
  ClipboardCopy,
  Building2,
  Fuel,
  RotateCcw,
  RefreshCw,
  TestTube,
  VolumeX,
  Video,
  GripVertical,
  ArrowUpDown,
  Play,
  Bug,
  Ban,
  HardDrive,
  ZoomIn,
  ZoomOut,
  ZapOff,
  CloudOff,
  ArrowRightLeft,
  ArrowLeftRight,
  
  // Weather & Environment
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  Wind,
  Thermometer,
  
  // Miscellaneous
  HelpCircle,
  HelpCircle as QuestionMark,
  Lightbulb,
  Target,
  Award,
  Gift,
  ShoppingCart,
  Package,
  Home,
  Map,
  Globe,
  Link,
  ExternalLink,
  Copy,
  Scissors,
  Paperclip,
  Archive,
  Trash,
  Share,
  Printer,
  Scan,
  QrCode,
  Barcode } from 'lucide-react';

// Central icon mapping - change icons here to update globally
export const ICON_MAP = {
  // Navigation & Actions
  add: Plus,
  plus: Plus,
  remove: Minus,
  minus: Minus,
  edit: Edit,
  pencil: Edit,
  delete: Trash2,
  trash: Trash2,
  close: X,
  cancel: X,
  check: Check,
  confirm: Check,
  search: Search,
  find: Search,
  filter: Filter,
  expandDown: ChevronDown,
  expandUp: ChevronUp,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  
  // Business & Finance
  car: Car,
  vehicle: Car,
  building: Building,
  company: Building,
  user: User,
  person: User,
  users: Users,
  people: Users,
  calendar: Calendar,
  date: Calendar,
  clock: Clock,
  time: Clock,
  creditCard: CreditCard,
  payment: CreditCard,
  euro: Euro,
  money: Euro,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  barChart: BarChart3,
  chart: BarChart3,
  pieChart: PieChart,
  percent: Percent,
  
  // Missing icons from migration
  pending: Clock,
  handover: Car,
  return: Car,
  pdf: FileText,
  gallery: Image,
  clear: X,
  export: Download,
  viewAgenda: List,
  viewComfy: Grid,
  viewColumn: Columns,
  report: FileText,
  bank: Building,
  receipt: Receipt,
  assessment: BarChart3,
  stats: TrendingUp,
  speed: Zap,
  personAdd: UserPlus,
  admin: Shield,
  employee: User,
  tempWorker: User,
  mechanic: Wrench,
  sales: TrendingUp,
  insurance: Shield,
  stk: CheckCircle,
  ek: CheckCircle,
  km: Car,
  document: FileText,
  maintenance: Wrench,
  active: CheckCircle,
  
  // Additional mappings for missing icons
  speedOutlined: Gauge,
  calculate: Calculator,
  discountIcon: Percent,
  clearIcon: X,
  exportIcon: Download,
  pdfIcon: FileText,
  bankIcon: Building2,
  reportIcon: FileBarChart,
  personAddIcon: UserPlus,
  securityIcon: Shield,
  fuelIcon: Fuel,
  documentIcon: FileText,
  maintenanceIcon: Wrench,
  insuranceIcon: Shield,
  stkIcon: CheckCircle,
  ekIcon: CheckCircle,
  kmIcon: Car,
  keyboardArrowDownIcon: ChevronDown,
  dashboardIcon: BarChart3,
  accountBalanceIcon: Building,
  percentIcon: Percent,
  autoFixHighIcon: Wand2,
  contentPasteIcon: ClipboardCopy,
  protocolIcon: FileText,
  galleryIcon: Users,
  handoverProtocolIcon: Car,
  returnProtocolIcon: Car,
  pendingIcon: Clock,
  activeIcon: CheckCircle,
  adminIcon: Shield,
  userIcon: User,
  employeeIcon: User,
  tempWorkerIcon: User,
  mechanicIcon: Wrench,
  salesIcon: TrendingUp,
  companyIcon: Building,
  statsIcon: BarChart3,
  speedIcon: Activity,
  assessmentIcon: BarChart3,
  showChartIcon: TrendingUp,
  viewAgendaIcon: List,
  viewComfyIcon: Grid,
  viewColumnIcon: Columns,
  
  // Missing icons from mass replacement
  fuel: Fuel,
  repeat: RotateCcw,
  generate: Zap,
  event: Calendar,
  claim: AlertTriangle,
  build: Wrench,
  assignment: FileText,
  sort: ArrowUpDown,
  discount: Percent,
  autoFixHigh: Wand2,
  contentPaste: ClipboardCopy,
  protocol: FileText,
  handoverProtocol: Car,
  returnProtocol: Car,
  keyboardArrowDown: ChevronDown,
  dashboard: BarChart3,
  accountBalance: Building,
  showChart: TrendingUp,
  
  // PWA & Notifications
  install: Download,
  installIcon: Download,
  updateIcon: RefreshCw,
  clearCacheIcon: Trash2,
  notificationIcon: Bell,
  notificationsActive: Bell,
  notificationsOff: BellOff,
  notificationsActiveIcon: Bell,
  testIcon: TestTube,
  quietIcon: VolumeX,
  phoneIcon: Phone,
  
  // Video & Media
  videoCall: Video,
  preview: Eye,
  
  // Company & Documents
  contractIcon: FileText,
  invoiceIcon: Receipt,
  
  // Email Management
  startIcon: Play,
  stopIcon: Square,
  
  // Categories & Expenses
  categoryIcon: Tag,
  dragIcon: GripVertical,
  serviceIcon: Wrench,
  otherIcon: MoreHorizontal,
  
  // Missing MUI icons
  groupIcon: Users,
  timelineIcon: Clock,
  analyticsIcon: BarChart3,
  blockIcon: Ban,
  memoryIcon: HardDrive,
  accountIcon: User,
  bugReportIcon: Bug,
  bugIcon: Bug,
  zoomInIcon: ZoomIn,
  navigateBefore: ChevronLeft,
  navigateNext: ChevronRight,
  zoomOut: ZoomOut,
  zoomIn: ZoomIn,
  flashOff: ZapOff,
  flipCameraIos: RotateCcw,
  cloudOffIcon: CloudOff,
  syncIcon: RefreshCw,
  photoLibrary: Image,
  playArrow: Play,
  transferIcon: ArrowRightLeft,
  swapHoriz: ArrowLeftRight,
  
  // Communication
  mail: Mail,
  email: Mail,
  phone: Phone,
  call: Phone,
  message: MessageSquare,
  chat: MessageSquare,
  bell: Bell,
  notification: Bell,
  alert: AlertCircle,
  warning: AlertCircle,
  info: Info,
  information: Info,
  success: CheckCircle,
  error: XCircle,
  danger: AlertTriangle,
  
  // Files & Documents
  file: File,
  fileText: FileText,
  text: FileText,
  download: Download,
  upload: Upload,
  folder: Folder,
  folderOpen: FolderOpen,
  image: Image,
  photo: Image,
  camera: Camera,
  eye: Eye,
  view: Eye,
  eyeOff: EyeOff,
  hide: EyeOff,
  
  // Settings & Tools
  settings: Settings,
  config: Settings,
  cog: Cog,
  gear: Cog,
  wrench: Wrench,
  tool: Wrench,
  shield: Shield,
  security: Shield,
  lock: Lock,
  locked: Lock,
  unlock: Unlock,
  unlocked: Unlock,
  key: Key,
  database: Database,
  db: Database,
  server: Server,
  cloud: Cloud,
  
  // Status & Indicators
  circle: Circle,
  dot: Circle,
  square: Square,
  star: Star,
  favorite: Star,
  heart: Heart,
  like: Heart,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  flag: Flag,
  tag: Tag,
  label: Tag,
  bookmark: Bookmark,
  save: Bookmark,
  
  // Layout & UI
  menu: Menu,
  hamburger: Menu,
  grid: Grid,
  list: List,
  layout: Layout,
  maximize: Maximize,
  minimize: Minimize,
  rotate: RotateCcw,
  refresh: RefreshCw,
  reload: RefreshCw,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  
  // Time & Date
  calendarDays: CalendarDays,
  clock3: Clock3,
  timer: Timer,
  history: History,
  
  // Transportation
  truck: Truck,
  bus: Bus,
  plane: Plane,
  train: Train,
  bike: Bike,
  mapPin: MapPin,
  location: MapPin,
  navigation: Navigation,
  nav: Navigation,
  
  // Technology
  wifi: Wifi,
  wifi_off: WifiOff,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  battery: Battery,
  batteryLow: BatteryLow,
  power: Power,
  zap: Zap,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  
  // Weather & Environment
  sun: Sun,
  moon: Moon,
  cloudRain: CloudRain,
  rain: CloudRain,
  cloudSnow: CloudSnow,
  snow: CloudSnow,
  wind: Wind,
  thermometer: Thermometer,
  temp: Thermometer,
  
  // Miscellaneous
  help: HelpCircle,
  question: QuestionMark,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  target: Target,
  award: Award,
  gift: Gift,
  shoppingCart: ShoppingCart,
  cart: ShoppingCart,
  package: Package,
  home: Home,
  map: Map,
  globe: Globe,
  link: Link,
  externalLink: ExternalLink,
  copy: Copy,
  scissors: Scissors,
  cut: Scissors,
  paperclip: Paperclip,
  archive: Archive,
  trashIcon: Trash,
  share: Share,
  printer: Printer,
  print: Printer,
  scan: Scan,
  qrCode: QrCode,
  barcode: Barcode,
} as const;

export type IconName = keyof typeof ICON_MAP;

// Helper function to get icon component
export const getIcon = (name: IconName) => ICON_MAP[name];

// Helper function to check if icon exists
export const hasIcon = (name: string): name is IconName => name in ICON_MAP;
