#!/bin/bash

echo "☁️  CLOUDFLARE R2 STORAGE SETUP - BLACKRENT"
echo "=============================================="
echo ""

echo "🎯 Tento script vám pomôže nastaviť Cloudflare R2 storage pre BlackRent aplikáciu."
echo ""

echo "📋 PREDPOKLADY:"
echo "✅ Máte Cloudflare účet (zadarmo na cloudflare.com)"
echo "✅ Máte prístup k Railway dashboard"
echo ""

echo "🚀 KROK 1: Vytvorenie Cloudflare R2 bucket"
echo "-------------------------------------------"
echo "1. Choďte na https://dash.cloudflare.com"
echo "2. Kliknite na 'R2 Object Storage'"
echo "3. Kliknite 'Create bucket'"
echo "4. Názov bucket: blackrent-storage"
echo "5. Location: Automatic (global)"
echo "6. Kliknite 'Create bucket'"
echo ""

echo "🔑 KROK 2: Vytvorenie API Token"
echo "-------------------------------"
echo "1. V R2 dashboard kliknite 'Manage API Tokens'"
echo "2. Kliknite 'Create Token'"
echo "3. Permissions:"
echo "   ✅ Object:Edit"
echo "   ✅ Object:Read"
echo "4. Bucket: blackrent-storage"
echo "5. Kliknite 'Create Token'"
echo "6. SKOPÍRUJTE si token!"
echo ""

echo "📝 KROK 3: Získanie Connection Details"
echo "-------------------------------------"
echo "1. V R2 bucket kliknite 'Settings' tab"
echo "2. Skopírujte:"
echo "   - Endpoint URL (https://xxx.r2.cloudflarestorage.com)"
echo "   - Account ID"
echo ""

echo "🌐 KROK 4: Nastavenie Public URL"
echo "-------------------------------"
echo "1. V R2 bucket kliknite 'Settings'"
echo "2. 'Custom domain' → 'Connect domain'"
echo "3. Domain: blackrent-storage.xxx.r2.dev (automaticky)"
echo "4. Enable public access"
echo ""

echo "⚙️  KROK 5: Railway Environment Variables"
echo "----------------------------------------"
echo "1. Choďte na Railway dashboard"
echo "2. Váš BlackRent project"
echo "3. Kliknite 'Variables' tab"
echo "4. Pridajte tieto premenné:"
echo ""

echo "R2_ENDPOINT=https://xxx.r2.cloudflarestorage.com"
echo "R2_BUCKET_NAME=blackrent-storage"
echo "R2_ACCESS_KEY_ID=your-access-key"
echo "R2_SECRET_ACCESS_KEY=your-secret-key"
echo "R2_ACCOUNT_ID=your-account-id"
echo "R2_PUBLIC_URL=https://blackrent-storage.xxx.r2.dev"
echo ""

echo "🔄 KROK 6: Redeploy aplikácie"
echo "----------------------------"
echo "1. Po pridaní všetkých premenných"
echo "2. Railway automaticky redeploy aplikácie"
echo "3. Čakajte 1-2 minúty"
echo ""

echo "🧪 KROK 7: Testovanie"
echo "-------------------"
echo "1. Vytvorte nový protokol s fotkami"
echo "2. Skontrolujte či sa fotky zobrazujú"
echo "3. Stiahnite PDF protokol"
echo "4. Skontrolujte či sú fotky v PDF"
echo ""

echo "📊 VÝHODY PO NASTAVENÍ:"
echo "✅ Všetky fotky a dokumenty v cloude"
echo "✅ Rýchle načítanie cez CDN"
echo "✅ Automatické zálohovanie"
echo "✅ 90% lacnejšie ako AWS S3"
echo "✅ Žiadne egress poplatky"
echo ""

echo "🎯 PO NASTAVENÍ BUDETE MAŤ:"
echo "✅ Profesionálne cloud storage"
echo "✅ Rýchle načítanie fotiek"
echo "✅ PDF protokoly s fotkami"
echo "✅ Digitálne podpisy"
echo "✅ Automatické zálohovanie"
echo ""

echo "💡 TIP: Ak máte problémy, skontrolujte:"
echo "- Všetky environment variables sú nastavené"
echo "- Railway redeploy je dokončený"
echo "- R2 bucket má public access"
echo ""

echo "🚀 PRIPRAVENÉ NA NASTAVENIE!"
echo "Spustite tento script znova ak potrebujete pomôcť." 