/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "colors-black-100": "var(--colors-black-100)",
        "colors-black-1000": "var(--colors-black-1000)",
        "colors-black-200": "var(--colors-black-200)",
        "colors-black-300": "var(--colors-black-300)",
        "colors-black-400": "var(--colors-black-400)",
        "colors-black-500": "var(--colors-black-500)",
        "colors-black-600": "var(--colors-black-600)",
        "colors-black-700": "var(--colors-black-700)",
        "colors-black-800": "var(--colors-black-800)",
        "colors-black-900": "var(--colors-black-900)",
        "colors-dark-gray-100": "var(--colors-dark-gray-100)",
        "colors-dark-gray-1000": "var(--colors-dark-gray-1000)",
        "colors-dark-gray-200": "var(--colors-dark-gray-200)",
        "colors-dark-gray-300": "var(--colors-dark-gray-300)",
        "colors-dark-gray-400": "var(--colors-dark-gray-400)",
        "colors-dark-gray-500": "var(--colors-dark-gray-500)",
        "colors-dark-gray-600": "var(--colors-dark-gray-600)",
        "colors-dark-gray-700": "var(--colors-dark-gray-700)",
        "colors-dark-gray-800": "var(--colors-dark-gray-800)",
        "colors-dark-gray-900": "var(--colors-dark-gray-900)",
        "colors-dark-yellow-accent-100": "var(--colors-dark-yellow-accent-100)",
        "colors-dark-yellow-accent-1000":
          "var(--colors-dark-yellow-accent-1000)",
        "colors-dark-yellow-accent-200": "var(--colors-dark-yellow-accent-200)",
        "colors-dark-yellow-accent-300": "var(--colors-dark-yellow-accent-300)",
        "colors-dark-yellow-accent-400": "var(--colors-dark-yellow-accent-400)",
        "colors-dark-yellow-accent-500": "var(--colors-dark-yellow-accent-500)",
        "colors-dark-yellow-accent-600": "var(--colors-dark-yellow-accent-600)",
        "colors-dark-yellow-accent-700": "var(--colors-dark-yellow-accent-700)",
        "colors-dark-yellow-accent-800": "var(--colors-dark-yellow-accent-800)",
        "colors-dark-yellow-accent-900": "var(--colors-dark-yellow-accent-900)",
        "colors-green-accent-100": "var(--colors-green-accent-100)",
        "colors-green-accent-1000": "var(--colors-green-accent-1000)",
        "colors-green-accent-200": "var(--colors-green-accent-200)",
        "colors-green-accent-300": "var(--colors-green-accent-300)",
        "colors-green-accent-400": "var(--colors-green-accent-400)",
        "colors-green-accent-500": "var(--colors-green-accent-500)",
        "colors-green-accent-600": "var(--colors-green-accent-600)",
        "colors-green-accent-700": "var(--colors-green-accent-700)",
        "colors-green-accent-800": "var(--colors-green-accent-800)",
        "colors-green-accent-900": "var(--colors-green-accent-900)",
        "colors-ligh-gray-100": "var(--colors-ligh-gray-100)",
        "colors-ligh-gray-1000": "var(--colors-ligh-gray-1000)",
        "colors-ligh-gray-200": "var(--colors-ligh-gray-200)",
        "colors-ligh-gray-300": "var(--colors-ligh-gray-300)",
        "colors-ligh-gray-400": "var(--colors-ligh-gray-400)",
        "colors-ligh-gray-500": "var(--colors-ligh-gray-500)",
        "colors-ligh-gray-600": "var(--colors-ligh-gray-600)",
        "colors-ligh-gray-700": "var(--colors-ligh-gray-700)",
        "colors-ligh-gray-800": "var(--colors-ligh-gray-800)",
        "colors-ligh-gray-900": "var(--colors-ligh-gray-900)",
        "colors-light-yellow-accent-100":
          "var(--colors-light-yellow-accent-100)",
        "colors-light-yellow-accent-1000":
          "var(--colors-light-yellow-accent-1000)",
        "colors-light-yellow-accent-200":
          "var(--colors-light-yellow-accent-200)",
        "colors-light-yellow-accent-300":
          "var(--colors-light-yellow-accent-300)",
        "colors-light-yellow-accent-400":
          "var(--colors-light-yellow-accent-400)",
        "colors-light-yellow-accent-500":
          "var(--colors-light-yellow-accent-500)",
        "colors-light-yellow-accent-600":
          "var(--colors-light-yellow-accent-600)",
        "colors-light-yellow-accent-700":
          "var(--colors-light-yellow-accent-700)",
        "colors-light-yellow-accent-800":
          "var(--colors-light-yellow-accent-800)",
        "colors-light-yellow-accent-900":
          "var(--colors-light-yellow-accent-900)",
        "colors-red-accent-100": "var(--colors-red-accent-100)",
        "colors-red-accent-200": "var(--colors-red-accent-200)",
        "colors-red-accent-300": "var(--colors-red-accent-300)",
        "colors-white-100": "var(--colors-white-100)",
        "colors-white-1000": "var(--colors-white-1000)",
        "colors-white-200": "var(--colors-white-200)",
        "colors-white-300": "var(--colors-white-300)",
        "colors-white-400": "var(--colors-white-400)",
        "colors-white-500": "var(--colors-white-500)",
        "colors-white-600": "var(--colors-white-600)",
        "colors-white-700": "var(--colors-white-700)",
        "colors-white-800": "var(--colors-white-800)",
        "colors-white-900": "var(--colors-white-900)",
      },
      fontFamily: {
        "desktop-titulok-40": "var(--desktop-titulok-40-font-family)",
        "mobil-text-mobil-14-reg": "var(--mobil-text-mobil-14-reg-font-family)",
        "test-filracia-nadpisy": "var(--test-filracia-nadpisy-font-family)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
