name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  frontend:
    name: Frontend (Vite)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (root)
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Test (Vitest)
        run: npm run test:run

  backend:
    name: Backend (Railway app)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (backend)
        working-directory: backend
        run: npm ci

      - name: Build backend
        working-directory: backend
        run: npm run build
