name: Daily Railway Backup

on:
  schedule:
    # Každý deň o 2:00 UTC (3:00 CET)
    - cron: '0 2 * * *'
  workflow_dispatch: # Umožní manuálne spustenie

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Railway Backup
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PGHOST: ${{ secrets.PGHOST }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          cd scripts/backup
          npm ci --production
          node railway-cron-backup.js

      - name: Backup Status
        if: success()
        run: |
          echo "✅ Daily backup completed successfully!"
          echo "📅 Date: $(date)"
          echo "🔗 Check R2 Storage for backup files"
      
      - name: Backup Failed
        if: failure()
        run: |
          echo "❌ Daily backup failed!"
          echo "📅 Date: $(date)"
          echo "🔍 Check logs above for details"
