name: Daily Railway Backup

on:
  schedule:
    # Každý deň o 2:00 UTC (3:00 CET)
    - cron: '0 2 * * *'
  workflow_dispatch: # Umožní manuálne spustenie

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run Database Backup
        env:
          PGHOST: trolley.proxy.rlwy.net
          PGUSER: postgres
          PGPORT: 13400
          PGDATABASE: railway
          PGPASSWORD: nfwrpKxILRUMqunYTZJEhjudEstqLRGv
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_BUCKET_NAME: blackrent-storage
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          echo "🚀 Running database backup..."
          cd scripts/backup
          npm install aws-sdk
          node railway-cron-backup.js

      - name: Backup Status
        run: |
          echo "✅ Daily backup completed successfully!"
          echo "📅 Date: $(date)"
          echo "🔗 Check R2 Storage for backup files"
